### ISSUE TITLE
Doesn't work whith leading whitespace

### ISSUE THREAD

**Issue by Hasenn** [ProbablyClem/cargo-todo#11]
leading tabulation or whitespace makes it fail, as in
```rust
    //todo the stuff i need to do
```
`^\N*\/\/todo *(\N*?)$` would capture your arguments and not cause that issue
https://regex101.com/r/dM5yP5/1/

**Comment by Hasenn** [comment]
I have found those in the source
```rust
b"^s*//s*todo\\b\n"
b"^s*//s*fix\\b\n"
b"^s*//s*fixme\\b\n"
```
I'm not sure if these are escaped by rust like rstrings would be, but they are broken
s matches an s character, and not \s which would match all whitespace characters.
This is maybe escaped by code ? But even then \s would match newlines and could parse more than intended, and not work with comments at the end of a code line

**Comment by ProbablyClem** [comment]
Fixed it, ty for the feedback
