### ISSUE TITLE
todo!() and unimplemented!() are not legacy in rust

### ISSUE THREAD

**Issue by Hasenn** [ProbablyClem/cargo-todo#13]
the readme seems to suggest that they are, and the legacy mode really shouldn't exist

**Comment by Hasenn** [comment]
Moreover, unimplemented!() is not a todo
[rust doc](https://doc.rust-lang.org/std/macro.todo.html) says :

"The difference between unimplemented! and todo! is that while todo! conveys an intent of implementing the functionality later and the message is "not yet implemented", unimplemented! makes no such claims. Its message is "not implemented". Also some IDEs will mark todo!s."

**Comment by ProbablyClem** [comment]
The legacy mode doesn't imply that todo!() and unimplemented!() are legacy within the std.
It's for a project that's already written and where you don't want to rewrite all your todos with the cargo-todo info (member, priority, ...).
If you're starting a project from scratch, you'd better use them, but most of the time you don't write to spend times on formating older todos.
