### ISSUE TITLE
Check if Cargo.toml is in the current directory

### ISSUE THREAD

**Issue by AldaronLau** [ProbablyClem/cargo-todo#6]
It would be useful if instead of when I first tried it, having it search my entire home directory, it would stop with a message like "Current directory is not a Cargo project".

**Comment by ProbablyClem** [comment]
The problem with such control is that it will stop you from checking todos only within a specific folder.
If you work on a large project, you probably just wanna see the todos within the crate/directory your working in.
And you can do such by just lauching the scan from the right place.
The solution is just to add the path you wanna check as parameter.
Maybe I'll do it someday.
