### ISSUE TITLE
What and why is foo.txt?

### ISSUE THREAD

**Issue by AldaronLau** [ProbablyClem/cargo-todo#7]
This doesn't seem like something that should be in created in the project directory.  It might be related to this mssage:
> File '~/.cargo/todo_config' not found, creating it

Strangely, it never creates that file.  So I'm guessing the contents that are supposed to be written to ~/.cargo/todo_config are actually written to ./foo.txt

**Comment by ProbablyClem** [comment]
I guess i know what's the problem i'll give a look thank you

**Comment by ProbablyClem** [comment]
This should have been fixed a while ago. Hit me up if it still happens

**Comment by AldaronLau** [comment]
Thank you.  Looks like it's fixed!
