### ISSUE TITLE
Doesn't work as a cargo subcommand

### ISSUE THREAD

**Issue by samuelvanderwaal** [ProbablyClem/cargo-todo#8]
When I install it and run it with `cargo todo` I get the following error:

`error: Found argument 'todo' which wasn't expected, or isn't valid in this context`

I believe how cargo works is it passes both the filename and the command extension to the subcommand invocation, so: `cargo-todo todo <args>`. I'm not sure exactly why it does this but I think you will need to handle the extra `todo` argument if you want this work as a proper cargo subcommand.

**Comment by ProbablyClem** [comment]
Hmm weird cause it works for me.
Are you on linux ?
What's your cargo directory ?
in which directory does cargo installed this program ?

**Comment by AldaronLau** [comment]
The cargo subcommand doesn't work for me either.  I'm on Linux (Fedora) and the program is at ~/.cargo/bin/cargo-todo.  @ProbablyClem What OS are you on?

**Comment by samuelvanderwaal** [comment]
> Hmm weird cause it works for me.
> Are you on linux ?
> What's your cargo directory ?
> in which directory does cargo installed this program ?

Manjaro Linux
`~/.cargo`
`~/.cargo/bin`

**Comment by samuelvanderwaal** [comment]
I created Pull Request #10 to show an example of how you might handle this. You can make an optional argument at index 1 that handles the `todo` value passed from `cargo` when the binary is called as a cargo subcommand. This still allows you to run the binary directly with `cargo run` or calling it directly `./cargo_todo`.

**Comment by waynexia** [comment]
Hi @ProbablyClem, Just a friendly ping.

This doesn't work for me (Linux, binary under `~/.cargo/bin/cargo-todo` ) either. What is the status of this issue?

**Comment by ProbablyClem** [comment]
Sorry for the wait, i merged @samuelvanderwaal solution. Thanks
