### ISSUE TITLE
Default Regex?

### ISSUE THREAD

**Issue by AldaronLau** [ProbablyClem/cargo-todo#9]
The default regex file:
```
^s*//s*todo\b
^s*//s*fix\b
^s*//s*fixme\b
```
matches
 - `//todo`, `//stodo`, `//sstodo`, `//ssstodo`, etc.
 - `//fix`,  `//sfix`, `//ssfix`, `//sssfix`, etc.
 - `//fixme` `//sfixme`, `//ssfixme`, `//sssfixme`, etc.

What I'm wondering is why that's the default.  I have never seen anyone use `//stodo` before.  I think something like
`// todo` should be matched by default.  Unfortunately, when I change the regex I get

> src/main.rs line: 1 // 
> TODO: my todo message

instead of (with the default regex and no space):

> src/main.rs line: 1 // TODO:
> my todo message

Here's the regex file (`~/.cargo/todo_config`) I used:
```
^s*//.todo\b
^s*//.fix\b
^s*//.fixme\b
```

**Comment by xmo-odoo** [comment]
I think the regex are in error and were probably intended to be `^\s*//\s*todo\b`, as in:

* start of line
* any amount of whitespace
* inline comment
* any amount of whitespace
* todo
* word separator

this way both `//todo` and `// todo` would work fine.

**Comment by ProbablyClem** [comment]
@xmo-odoo is right !
I fixed it, it will be in the next release.
If you're still alive (and still using cargo-todo) you can either delete the config file so the new default will be generated or update it by yourself.
Sorry for the latency, I'm really busy irl.
Don't hesitate to do pull requests if you have any other issue.
Thanks
